site_name: 《explore flask》中文翻译

# 配置主题，在mkdocs.yml文件下
theme:
  name: material
  language: zh

nav:
  - README: README.md
  - 封面: cover.md
  - 前言: 1-introduction.md
  - 代码约定: 2-coding_conventions.md
  - 环境: 3-environment.md
  - 组织你的项目: 4-organizing_your_project.md
  - 配置: 5-configuration.md
  - 关于视图和路由的进阶技巧: 6-advanced_patterns_for_views_and_routing.md
  - 蓝图: 7-blueprints.md
  - 模板: 8-templates.md
  - 静态文件: 9-static_files.md
  - 存储: 10-storing-data.md
  - 处理表单: 11-handling_forms.md
  - 用户管理的规范: 12-handling_users.md
  - 部署: 13-deployment.md
  - 结语: 14-conclusion.md

